### ISSUE TITLE
Create benchmark configs

### ISSUE THREAD

**Issue by HiroakiMikami** [HiroakiMikami/mlprogram#165]
### Purpuse

Create benchmark configs to compare different algorithms

### Requirements

* 1 dataset per 1 task (e.g., PbE, natural language to program, etc.)
* training within 1 hours (CPU/GPU)
* small: evaluation within 15 minutes (CPU)
* large: evaluation within 1 hours (CPU)

**Comment by HiroakiMikami** [comment]
* NL2Prog
    * Dataset: Hearthstone
    * Training: about 20 epoch (CPU)
    * Evaluation timeout (66samples): 15sec (small), 180sec (large)
* PbE (w/o input)
    * Dataset: CSG
    * Training: 6000iter (CPU)
    * Evaluation timeout (30samples): 30sec (small), 360sec (large)
* auto repair

**Comment by HiroakiMikami** [comment]
### TODO

* [x] CSG (small) should increase the problem size (?)
     * baseline model -> small evaluation => generation-rate=50%
* [x] Select CPU/GPU for benchmarking
* [x] Benchmark script
* [x] Disable multiprocess evaluation. Handle same as distributed training If want to do so.

**Comment by HiroakiMikami** [comment]
### Notes

* Hearthstone training throughput, baseline LSTM model
    * w/ CPU (my local desktop, WSL2): about 3 min / epoch (300ms /sample @ 1 process, 250ms/sample @ 2process 225ms/sample @ 4process w/ `OMP_NUM_THREADS=1`)
    * w/ GPU (Colab): about 2.5~3 min / epoch
