### ISSUE TITLE
Use gin-config to launch training, evaluation, etc.

### ISSUE THREAD

**Issue by HiroakiMikami** [HiroakiMikami/mlprogram#27]
* [x] Add `external_configurables`
* [x] Add `tools/launch.py`
* [x] Rename and change `examples` to `configs`

**Comment by HiroakiMikami** [comment]
To handle dataset and encoder (the objects that do not exist when launching), I can use a global dictionary.

Experiment with REPL:

```python
>>> import gin
>>> workspace = {}
>>> @gin.configurable
... def get(name: str):
...    return workspace[name]
... 
>>> @gin.configurable
... def double(x: int):
...    return x * 2
... 
>>> gin.parse_config("double.x = @get()\nget.name = 'foo'")
>>> workspace["foo"] = 10
>>> double()
20
```

**Comment by HiroakiMikami** [comment]
### TODO

* [x] How to create optimizer (it's difficult to set parameter groups)
* [x] Rewrite test cases by using gin.config

**Comment by HiroakiMikami** [comment]
### TODO

* [ ] How to save/load the training results
* [ ] How to store checkpoints to disk
* [ ] Replace examples with configs
